version: "3.9"

services:
  yolo-train:
    image: draiv-dev:0.1  # Replace with your Docker image tag
    command: >
      yolo detect train
        model=yolo12m.pt
        project=/workspace/runs/my_yolo_experiments
        name=yolo12m_01
        epochs=100
        batch=48
        imgsz=640
        half=True
        cache=labels
        workers=10
        cos_lr=True
        warmup_epochs=3
        save_period=5
        data=/workspace/configs/bdd100k_det.yaml
    environment:
      - ULTRALYTICS_WORKERS=10
      - ULTRALYTICS_NO_UPGRADE=1
    volumes:
      - /scratch/dannycharm-alt-REU/DRAIV/datasets:/datasets
      - /scratch/dannycharm-alt-REU/DRAIV:/workspace
      - /scratch/dannycharm-alt-REU/DRAIV/runs:/workspace/runs
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]  # Requires Docker Compose v3+ and NVIDIA runtime
    shm_size: "64gb"
    restart: "no"

